### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by fului**
I have added fileLength to the media modal view, to be able to see how long the video is.

I also changed a check to also be able to handle `null`.

### CODE REVIEW

**Comment by B-Interactive** [comment]
Thank you @fului!

**Comment by fului** [comment]
You are welcome @B-Interactive 

Could you also add a new tag/release, so that these changes get into their own release?

I would suggest using something like npm semantic release in actions, so that a new release is created automatically, from the commit messages, when something is merged into the main branch. 

I'll create a new branch with the config files for semantic release and conventional commits, however I only have experience with creating ci pipelines in gitlab, so I'm not sure how to get the GitHub actions working for this.

**Comment by B-Interactive** [comment]
That's now a [tagged release](https://github.com/B-Interactive/cloudflare-stream-wordpress/releases/tag/1.0.9.5).

I'd love to have the release process automated as you've suggested.  I've yet been able to commit time to figure out though, so contributions are of course, very welcome.

**Comment by fului** [comment]
That's fine, I'll try and do it. 

I will also create a few other issues and work on them, to contribute to this plugin, as I want to contribute a bit to some open source projects.

**Pull request merged**
